[2024-05-24T08:51:32.685+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T08:51:32.723+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v3.third_task scheduled__2024-05-21T00:00:00+00:00 [queued]>
[2024-05-24T08:51:32.733+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v3.third_task scheduled__2024-05-21T00:00:00+00:00 [queued]>
[2024-05-24T08:51:32.735+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-24T08:51:32.746+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): third_task> on 2024-05-21 00:00:00+00:00
[2024-05-24T08:51:32.753+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1977) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-24T08:51:32.754+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v3', 'third_task', 'scheduled__2024-05-21T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmphsu47ops']
[2024-05-24T08:51:32.755+0000] {standard_task_runner.py:63} INFO - Started process 1988 to run task
[2024-05-24T08:51:32.756+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask third_task
[2024-05-24T08:51:32.800+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v3.third_task scheduled__2024-05-21T00:00:00+00:00 [running]> on host 6bbd6353fbe6
[2024-05-24T08:51:32.862+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gauti' AIRFLOW_CTX_DAG_ID='our_first_dag_v3' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-21T00:00:00+00:00'
[2024-05-24T08:51:32.863+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T08:51:32.872+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-24T08:51:32.875+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task 3 and I will run after task1 but at the same time as task2....']
[2024-05-24T08:51:32.881+0000] {subprocess.py:86} INFO - Output:
[2024-05-24T08:51:32.881+0000] {subprocess.py:93} INFO - hey, I am task 3 and I will run after task1 but at the same time as task2....
[2024-05-24T08:51:32.882+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-24T08:51:32.883+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T08:51:32.897+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v3, task_id=third_task, run_id=scheduled__2024-05-21T00:00:00+00:00, execution_date=20240521T000000, start_date=20240524T085132, end_date=20240524T085132
[2024-05-24T08:51:32.937+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T08:51:32.946+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T08:51:32.947+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
