[2024-05-24T09:23:17.053+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-24T09:23:17.069+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.third_task scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-24T09:23:17.077+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.third_task scheduled__2024-05-20T00:00:00+00:00 [queued]>
[2024-05-24T09:23:17.077+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-05-24T09:23:17.086+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): third_task> on 2024-05-20 00:00:00+00:00
[2024-05-24T09:23:17.090+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2551) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-24T09:23:17.091+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'third_task', 'scheduled__2024-05-20T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpwsri0vvj']
[2024-05-24T09:23:17.094+0000] {standard_task_runner.py:63} INFO - Started process 2562 to run task
[2024-05-24T09:23:17.094+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask third_task
[2024-05-24T09:23:17.127+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dag_v5.third_task scheduled__2024-05-20T00:00:00+00:00 [running]> on host 6bbd6353fbe6
[2024-05-24T09:23:17.184+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='gauti' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-20T00:00:00+00:00'
[2024-05-24T09:23:17.185+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-24T09:23:17.193+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-24T09:23:17.194+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task 3 and I will run after task1 but at the same time as task2....']
[2024-05-24T09:23:17.198+0000] {subprocess.py:86} INFO - Output:
[2024-05-24T09:23:17.199+0000] {subprocess.py:93} INFO - hey, I am task 3 and I will run after task1 but at the same time as task2....
[2024-05-24T09:23:17.203+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-24T09:23:17.204+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-24T09:23:17.214+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=third_task, run_id=scheduled__2024-05-20T00:00:00+00:00, execution_date=20240520T000000, start_date=20240524T092317, end_date=20240524T092317
[2024-05-24T09:23:17.235+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-24T09:23:17.242+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-24T09:23:17.243+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
